sudo: required
services:
  - docker

before_install:
  - docker build -t asprague/client -f Dockerfile.dev .

script:
  - docker run -e CI=true asprague/client npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-client"
  env: "DockerClient-env"
  bucket_name: "elasticbeanstalk-us-east-2-675428214133"
  bucket_path: "docker-client"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
